# Generated by Django 5.2.6 on 2025-10-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('ckan_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('notes', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('author_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('maintainer', models.CharField(blank=True, max_length=255, null=True)),
                ('maintainer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('organization_id', models.CharField(blank=True, max_length=36, null=True)),
                ('organization_title', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('license_id', models.CharField(blank=True, max_length=50, null=True)),
                ('license_title', models.CharField(blank=True, max_length=255, null=True)),
                ('license_url', models.URLField(blank=True, null=True)),
                ('metadata_created', models.DateTimeField(blank=True, null=True)),
                ('metadata_modified', models.DateTimeField(blank=True, null=True)),
                ('temporal', models.CharField(blank=True, max_length=100, null=True)),
                ('update_frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('private', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('groups', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
