# Generated by Django 5.2.7 on 2025-10-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TP1_Inforoute', '0004_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='created',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
